/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_sergiosuazo;

import com.sun.security.ntlm.Client;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Workstation DSY
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    public Principal() {
        initComponents();
        aa=new adminATM("./ATM.sas");
        aa.cargarArchivo();
        DefaultComboBoxModel m = (DefaultComboBoxModel)cb_ATM.getModel();
        for (int i = 0; i < aa.getListaATM().size(); i++) {
            m.addElement(aa.getListaATM().get(i));
        }
        cb_ATM.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Crear = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_nombre2 = new javax.swing.JTextField();
        tf_apellido1 = new javax.swing.JTextField();
        tf_apellido2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        dc_afiliacion = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jd_Cliente = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jd_Mantenimiento = new javax.swing.JDialog();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        sp_500 = new javax.swing.JSpinner();
        sp_100 = new javax.swing.JSpinner();
        jButton12 = new javax.swing.JButton();
        jd_ATM = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_ubicacion = new javax.swing.JTextField();
        dc_fabricacion = new com.toedter.calendar.JDateChooser();
        tf_mantenimiento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jd_CrearMantenimiento = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_nombre1M = new javax.swing.JTextField();
        tf_nombre2M = new javax.swing.JTextField();
        tf_apellido1M = new javax.swing.JTextField();
        tf_apellido2M = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_usuario1 = new javax.swing.JTextField();
        tf_contra1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dc_fecha1 = new com.toedter.calendar.JDateChooser();
        dc_afiliacion1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_ATM = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jd_Retirar = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cb_miCuenta = new javax.swing.JComboBox<>();
        rb_100 = new javax.swing.JRadioButton();
        rb_500 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        bg_retirar = new javax.swing.ButtonGroup();
        jd_Ingresar = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        cb_miCuenta1 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        rb_100i = new javax.swing.JRadioButton();
        rb_500i = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jd_Transferencia = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        sp_monto = new javax.swing.JSpinner();
        cb_miCuenta2 = new javax.swing.JComboBox<>();
        cb_transferir = new javax.swing.JComboBox<>();
        cb_cuentaTransferir = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jd_EstadoCuenta = new javax.swing.JDialog();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cb_miCuenta3 = new javax.swing.JComboBox<>();
        tf_miSaldo = new javax.swing.JTextField();
        jd_Transacciones = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_transacciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cb_ATM = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel9.setText("Nombre:");

        jLabel10.setText("Apellido:");

        jLabel11.setText("Segundo Nombre:");

        jLabel12.setText("Segundo Apellido: ");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        jLabel15.setText("Fecha de nacimiento:");

        jLabel16.setText("Fecha de afiliacion:");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearLayout = new javax.swing.GroupLayout(jd_Crear.getContentPane());
        jd_Crear.getContentPane().setLayout(jd_CrearLayout);
        jd_CrearLayout.setHorizontalGroup(
            jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearLayout.createSequentialGroup()
                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearLayout.createSequentialGroup()
                                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre1)
                                    .addComponent(tf_nombre2)
                                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearLayout.createSequentialGroup()
                                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_apellido1)
                                    .addComponent(tf_apellido2)
                                    .addComponent(tf_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(jd_CrearLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(dc_afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_CrearLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jd_CrearLayout.setVerticalGroup(
            jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("Retirar Dinero");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Ingresar Dinero");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Transferencia");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jMenu2.setText("Opciones");

        jMenuItem4.setText("Crear Cuenta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Ver estado de cuenta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ver Transacciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar2.add(jMenu2);

        jd_Cliente.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jd_ClienteLayout = new javax.swing.GroupLayout(jd_Cliente.getContentPane());
        jd_Cliente.getContentPane().setLayout(jd_ClienteLayout);
        jd_ClienteLayout.setHorizontalGroup(
            jd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ClienteLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(89, 89, 89))
        );
        jd_ClienteLayout.setVerticalGroup(
            jd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ClienteLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Mantenimiento de ATM");

        jLabel39.setText("Bileltes de 100:");

        jLabel40.setText("Billetes de 500:");

        jButton12.setText("Ingresar al ATM");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_MantenimientoLayout = new javax.swing.GroupLayout(jd_Mantenimiento.getContentPane());
        jd_Mantenimiento.getContentPane().setLayout(jd_MantenimientoLayout);
        jd_MantenimientoLayout.setHorizontalGroup(
            jd_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MantenimientoLayout.createSequentialGroup()
                .addGroup(jd_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_MantenimientoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel38))
                    .addGroup(jd_MantenimientoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_100, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sp_500, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_MantenimientoLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton12)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jd_MantenimientoLayout.setVerticalGroup(
            jd_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(31, 31, 31)
                .addGroup(jd_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(sp_500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(26, 26, 26))
        );

        jLabel5.setText("Ubicacion:");

        jLabel6.setText("Fecha de fabricacion:");

        jLabel7.setText("Mantenimiento: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Registrar un ATM");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ATMLayout = new javax.swing.GroupLayout(jd_ATM.getContentPane());
        jd_ATM.getContentPane().setLayout(jd_ATMLayout);
        jd_ATMLayout.setHorizontalGroup(
            jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ATMLayout.createSequentialGroup()
                .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ATMLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jButton2)))
                    .addGroup(jd_ATMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_ATMLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ATMLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(dc_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ATMLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_mantenimiento)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jd_ATMLayout.setVerticalGroup(
            jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ATMLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_ATMLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(dc_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel17.setText("Nombre:");

        jLabel18.setText("Apellido:");

        jLabel19.setText("Segundo Nombre:");

        jLabel20.setText("Segundo Apellido: ");

        jLabel21.setText("Usuario:");

        jLabel22.setText("Contraseña:");

        jLabel23.setText("Fecha de nacimiento:");

        jLabel24.setText("Fecha de afiliacion:");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jl_ATM.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_ATM);

        jButton5.setText("Agregar ATM");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearMantenimientoLayout = new javax.swing.GroupLayout(jd_CrearMantenimiento.getContentPane());
        jd_CrearMantenimiento.getContentPane().setLayout(jd_CrearMantenimientoLayout);
        jd_CrearMantenimientoLayout.setHorizontalGroup(
            jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre1M)
                                    .addComponent(tf_nombre2M)
                                    .addComponent(tf_usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(dc_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_apellido1M)
                                    .addComponent(tf_apellido2M)
                                    .addComponent(tf_contra1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(dc_afiliacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton5))
                            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jd_CrearMantenimientoLayout.setVerticalGroup(
            jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearMantenimientoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(tf_nombre1M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_apellido1M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(tf_nombre2M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_apellido2M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(tf_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_CrearMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24))
                            .addComponent(dc_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_afiliacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearMantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addComponent(jButton5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel25.setText("Cuenta:");

        jLabel26.setText("Monto: ");

        bg_retirar.add(rb_100);
        rb_100.setText("100");

        bg_retirar.add(rb_500);
        rb_500.setText("500");

        jButton9.setText("Retirar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Retirar Dinero");

        javax.swing.GroupLayout jd_RetirarLayout = new javax.swing.GroupLayout(jd_Retirar.getContentPane());
        jd_Retirar.getContentPane().setLayout(jd_RetirarLayout);
        jd_RetirarLayout.setHorizontalGroup(
            jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RetirarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGroup(jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_RetirarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_RetirarLayout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jd_RetirarLayout.createSequentialGroup()
                                .addComponent(rb_100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_500))))
                    .addGroup(jd_RetirarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb_miCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jd_RetirarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_RetirarLayout.setVerticalGroup(
            jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RetirarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cb_miCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_RetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rb_100)
                    .addComponent(rb_500))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel27.setText("Cuenta:");

        jLabel29.setText("Monto:");

        bg_retirar.add(rb_100i);
        rb_100i.setText("100");

        bg_retirar.add(rb_500i);
        rb_500i.setText("500");

        jButton10.setText("Ingresar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Ingresar Monto");

        javax.swing.GroupLayout jd_IngresarLayout = new javax.swing.GroupLayout(jd_Ingresar.getContentPane());
        jd_Ingresar.getContentPane().setLayout(jd_IngresarLayout);
        jd_IngresarLayout.setHorizontalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_IngresarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_IngresarLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_miCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_IngresarLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10)
                                    .addGroup(jd_IngresarLayout.createSequentialGroup()
                                        .addComponent(rb_100i)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rb_500i))))))
                    .addGroup(jd_IngresarLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel30)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jd_IngresarLayout.setVerticalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cb_miCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(rb_100i)
                    .addComponent(rb_500i))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Transferencia");

        jLabel32.setText("Cuenta:");

        jLabel33.setText("Monto:");

        jLabel34.setText("Persona a la que le transfiere:");

        jLabel35.setText("Cuenta de la persona:");

        cb_transferir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_transferirItemStateChanged(evt);
            }
        });

        jButton11.setText("Transferir");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_TransferenciaLayout = new javax.swing.GroupLayout(jd_Transferencia.getContentPane());
        jd_Transferencia.getContentPane().setLayout(jd_TransferenciaLayout);
        jd_TransferenciaLayout.setHorizontalGroup(
            jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(10, 10, 10)
                                .addComponent(cb_miCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(sp_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cb_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_cuentaTransferir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel31)))
                .addGap(54, 54, 54))
            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_TransferenciaLayout.setVerticalGroup(
            jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31)
                        .addGap(34, 34, 34)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_cuentaTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_TransferenciaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_miCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(sp_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(22, 22, 22))
        );

        jLabel36.setText("Cuenta:");

        jLabel37.setText("Saldo:");

        cb_miCuenta3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_miCuenta3ItemStateChanged(evt);
            }
        });

        tf_miSaldo.setEditable(false);

        javax.swing.GroupLayout jd_EstadoCuentaLayout = new javax.swing.GroupLayout(jd_EstadoCuenta.getContentPane());
        jd_EstadoCuenta.getContentPane().setLayout(jd_EstadoCuentaLayout);
        jd_EstadoCuentaLayout.setHorizontalGroup(
            jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EstadoCuentaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_miCuenta3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_miSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jd_EstadoCuentaLayout.setVerticalGroup(
            jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EstadoCuentaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cb_miCuenta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_miSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jt_transacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Accion", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_transacciones);

        javax.swing.GroupLayout jd_TransaccionesLayout = new javax.swing.GroupLayout(jd_Transacciones.getContentPane());
        jd_Transacciones.getContentPane().setLayout(jd_TransaccionesLayout);
        jd_TransaccionesLayout.setHorizontalGroup(
            jd_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TransaccionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jd_TransaccionesLayout.setVerticalGroup(
            jd_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TransaccionesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistema de Cajero Automatico");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        tf_user.setEnabled(false);

        pf_contra.setEnabled(false);

        jLabel4.setText("ATM:");

        cb_ATM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ATMItemStateChanged(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Crear Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Crear Mantenimiento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Crear ATM");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(tf_user)
                            .addComponent(cb_ATM, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_ATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_ATMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ATMItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==2)
        {
            tf_user.setEnabled(true);
            pf_contra.setEnabled(true);
        }
    }//GEN-LAST:event_cb_ATMItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_Crear.setVisible(true);
        jd_Crear.pack();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jd_ATM.setVisible(true);
        jd_ATM.pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            Cliente c =new Cliente(tf_nombre1.getText(), tf_nombre2.getText(), tf_apellido1.getText(), tf_apellido2.getText(), tf_usuario.getText(), tf_contra.getText(), dc_fecha.getDate(), dc_afiliacion.getDate());
            ac=new adminCliente("./clientes.sas");
            ac.cargarArchivo();
            ac.setCliente(c);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Se creo el cliente exitosamente");
            tf_nombre1.setText("");
            tf_nombre2.setText("");
            tf_apellido1.setText("");
            tf_apellido2.setText("");
            tf_usuario.setText("");
            tf_contra.setText("");
            dc_fecha.setDate(new Date());
            dc_afiliacion.setDate(new Date());
            jd_Crear.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al crear el cliente");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {
            Mantenimiento m =new Mantenimiento(tf_nombre1M.getText(), tf_nombre2M.getText(), tf_apellido1M.getText(), tf_apellido2M.getText(), tf_usuario1.getText(), tf_contra1.getText(), dc_fecha1.getDate(), dc_afiliacion1.getDate());
            m.setAtm(atms);
            am=new adminMantenimiento("./mantenimiento.sas");
            am.cargarArchivo();
            am.setMantenimiento(m);
            am.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Se creo el usuario de mantenimiento exitosamente");
            tf_nombre1M.setText("");
            tf_nombre2M.setText("");
            tf_apellido1M.setText("");
            tf_apellido2M.setText("");
            tf_usuario1.setText("");
            tf_contra1.setText("");
            dc_fecha1.setDate(new Date());
            dc_afiliacion1.setDate(new Date());
            jd_CrearMantenimiento.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al crear el usuario");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_CrearMantenimiento.setVisible(true);
        jd_CrearMantenimiento.pack();
        DefaultListModel m=new DefaultListModel();
        aa=new adminATM("./ATM.sas");
        aa.cargarArchivo();
        for (int i = 0; i < aa.getListaATM().size(); i++) {
            m.addElement(aa.getListaATM().get(i));
        }
        jl_ATM.setModel(m);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if(jl_ATM.getSelectedIndex()>=0)
        {
            atms=new ArrayList<>();
            DefaultListModel m = (DefaultListModel)jl_ATM.getModel();
            atms.add((ATM) m.get(jl_ATM.getSelectedIndex()));
            m.remove(jl_ATM.getSelectedIndex());
            jl_ATM.setModel(m);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "no se selecciono ningun atm");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            boolean login=false;
            ac=new adminCliente("./clientes.sas");
            ac.cargarArchivo();
            for (int i = 0; i < ac.getListaClientes().size(); i++) {
                if(ac.getListaClientes().get(i).getUser().equals(tf_user.getText()))
                {
                    current=ac.getListaClientes().get(i);
                    atm_actual=(ATM)cb_ATM.getSelectedItem();
                    login=true;
                    break;
                }
            }
            am=new adminMantenimiento("./mantenimiento.sas");
            am.cargarArchivo();
            for (int i = 0; i < am.getListaMantenimiento().size(); i++) {
                if(am.getListaMantenimiento().get(i).getUser().equals(tf_user.getText()))
                {
                    current=am.getListaMantenimiento().get(i);
                    atm_actual=(ATM)cb_ATM.getSelectedItem();
                    for (int j = 0; j < am.getListaMantenimiento().get(i).getAtm().size(); j++) {
                        if(am.getListaMantenimiento().get(i).getAtm().get(j).equals(atm_actual))
                        {
                            login=true;
                            break;
                        }
                    }
                }
            }
            
            if(current instanceof Cliente && login)
            {
                jd_Cliente.setVisible(true);
                jd_Cliente.pack();
                Log l = new Log(current.getUser(), "Ingreso al sistema", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
            }
            else if (current instanceof Mantenimiento && login)
            {
                jd_Mantenimiento.setVisible(true);
                jd_Mantenimiento.pack();
                Log l = new Log(current.getUser(), "Ingreso al sistema", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
            }
            else if(current instanceof Mantenimiento && !login)
            {
                JOptionPane.showMessageDialog(this, "El usuario de mantenimiento no tiene permiso de entrar a este ATM, seleccione uno nuevo");
                Log l = new Log(current.getUser(), "Seleccion incorrecta de ATM del Usuario de mantenimiento", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "se ingresaron mal los datos");
                Log l = new Log(" ", "Ingreso fallido al sistema", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al ingresar los datos");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            int x=999+rand.nextInt(9999);
            ATM a=new ATM(x, 500, tf_ubicacion.getText(), tf_mantenimiento.getText(), dc_fabricacion.getDate());
            aa=new adminATM("./ATM.sas");
            aa.cargarArchivo();
            aa.setATM(a);
            aa.escribirArchivo();
            DefaultComboBoxModel m = (DefaultComboBoxModel)cb_ATM.getModel();
            m.addElement(a);
            cb_ATM.setModel(m);
            tf_ubicacion.setText("");
            tf_mantenimiento.setText("");
            dc_fabricacion.setDate(new Date());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al ingresar los datos");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel m=new DefaultComboBoxModel();
        ac=new adminCliente("./clientes.sas");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getListaClientes().size(); i++) {
            if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
            {
                m=new DefaultComboBoxModel(ac.getListaClientes().get(i).getCuentas().toArray());
            }
        }
        cb_miCuenta.setModel(m);
        jd_Retirar.setVisible(true);
        jd_Retirar.pack();
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        try {
            Cuenta temp;
            DefaultComboBoxModel m=(DefaultComboBoxModel)cb_miCuenta.getModel();
            temp=(Cuenta)m.getSelectedItem();
            int monto=0;
            int x=999+rand.nextInt(9999);
            if(rb_100.isSelected())
            {
                monto=100;
            }
            else if(rb_500.isSelected())
            {
                monto=500;
            }
            if(atm_actual.getDinero()-monto>=0)
            {
                if(temp.getSaldo()-monto>=0)
                {
                    
                    aa=new adminATM("./ATM.sas");
                    aa.cargarArchivo();
                    for (int i = 0; i < aa.getListaATM().size(); i++) {
                        if(aa.getListaATM().get(i).equals(atm_actual))
                        {
                            aa.getListaATM().get(i).setDinero(aa.getListaATM().get(i).getDinero()-monto);
                        }
                    }
                    aa.escribirArchivo();
                    ac=new adminCliente("./clientes.sas");
                    ac.cargarArchivo();
                    for (int i = 0; i < ac.getListaClientes().size(); i++) {
                        if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
                        {
                            for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                                if(ac.getListaClientes().get(i).getCuentas().get(j).equals(temp))
                                {
                                    ac.getListaClientes().get(i).getCuentas().get(j).setSaldo(ac.getListaClientes().get(i).getCuentas().get(j).getSaldo()-monto);
                                    Transaccion t = new Transaccion( ac.getListaClientes().get(i).getCuentas().get(j).getNombre(), x, "Retiro de dinero", new Date().toString());
                                    ac.getListaClientes().get(i).getMistransacciones().add(t);
                                    at=new adminTransaccion("./transacciones.txt");
                                    at.cargarArchivo();
                                    at.setTransaccion(t);
                                    at.escribirArchivo();
                                    break;
                                }
                            }
                            break;
                        }
                    }
                    ac.escribirArchivo();
                    Log l = new Log(current.getUser(), "retiro de dinero", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
                    JOptionPane.showMessageDialog(this, "retiro exitoso");
                    jd_Cliente.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "La cuenta no tiene la cantidad de dinero necesaria");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Disculpe, el ATM no tiene la cantidad de dinero suficiente para realizar esta accion");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al ingresar los datos");
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel m=new DefaultComboBoxModel();
        ac=new adminCliente("./clientes.sas");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getListaClientes().size(); i++) {
            if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
            {
                for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                    m.addElement(ac.getListaClientes().get(i).getCuentas().get(j));
                }
            }
        }
        cb_miCuenta1.setModel(m);
        jd_Ingresar.setVisible(true);
        jd_Ingresar.pack();
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        try {
            Cuenta temp;
            DefaultComboBoxModel m=(DefaultComboBoxModel)cb_miCuenta1.getModel();
            temp=(Cuenta)m.getSelectedItem();
            int x=999+rand.nextInt(9999);
            int monto=0;
            
            if(rb_100.isSelected())
            {
                monto=100;
            }
            else if(rb_500.isSelected())
            {
                monto=500;
            }

            aa=new adminATM("./ATM.sas");
            aa.cargarArchivo();
            for (int i = 0; i < aa.getListaATM().size(); i++) {
                if(aa.getListaATM().get(i).equals(atm_actual))
                {
                    aa.getListaATM().get(i).setDinero(aa.getListaATM().get(i).getDinero()+monto);
                }
            }
            aa.escribirArchivo();
            ac=new adminCliente("./clientes.sas");
            ac.cargarArchivo();
            for (int i = 0; i < ac.getListaClientes().size(); i++) {
                if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
                {
                    for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                        if(ac.getListaClientes().get(i).getCuentas().get(j).equals(temp))
                        {
                            ac.getListaClientes().get(i).getCuentas().get(j).setSaldo(ac.getListaClientes().get(i).getCuentas().get(j).getSaldo()+monto);
                            Transaccion t = new Transaccion(((Cliente)current).getCuentas().get(j).getNombre(), x, "Ingreso de dinero a la cuenta", new Date().toString());
                            at=new adminTransaccion("./transacciones.txt");
                            at.cargarArchivo();
                            at.setTransaccion(t);
                            at.escribirArchivo();
                            break;
                        }
                    }
                    break;
                }
            }
            Log l = new Log(current.getUser(), "Ingreso de dinero", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
            al=new adminLog("./log.txt");
            al.cargarArchivo();
            al.setLog(l);
            al.escribirArchivo();
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(this, "ingreso exitoso");
            jd_Cliente.dispose();

     
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al ingresar los datos");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        ac=new adminCliente("./clientes.sas");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getListaClientes().size(); i++) {
            if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
            {
                for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                    m.addElement(ac.getListaClientes().get(i).getCuentas().get(j));
                }
            }
        }
        cb_miCuenta2.setModel(m);
        DefaultComboBoxModel m1=new DefaultComboBoxModel();
        ac=new adminCliente("./clientes.sas");
        
        for (int i = 0; i < ac.getListaClientes().size(); i++) {
            if(!ac.getListaClientes().get(i).getUser().equals(current.getUser()))
            {
                m1.addElement(ac.getListaClientes().get(i));
            }
        }
        cb_transferir.setModel(m1);
        jd_Transferencia.setVisible(true);
        jd_Transferencia.pack();
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void cb_transferirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_transferirItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==2)
        {
            Cliente temp;
            DefaultComboBoxModel m=(DefaultComboBoxModel)cb_transferir.getModel();
            temp=(Cliente)m.getSelectedItem();
            DefaultComboBoxModel m1=new DefaultComboBoxModel();
            for (int i = 0; i < temp.getCuentas().size(); i++) {
                m1.addElement(temp.getCuentas().get(i));
            }
            cb_cuentaTransferir.setModel(m1);
        }
    }//GEN-LAST:event_cb_transferirItemStateChanged

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        try {
            Cuenta temp,temp2;
            Cliente tempC;
            int x=999+rand.nextInt(9999);
            DefaultComboBoxModel m=(DefaultComboBoxModel)cb_miCuenta2.getModel();
            temp=(Cuenta)m.getSelectedItem();
            DefaultComboBoxModel m1=(DefaultComboBoxModel)cb_transferir.getModel();
            tempC=(Cliente)m.getSelectedItem();
            DefaultComboBoxModel m2=(DefaultComboBoxModel)cb_cuentaTransferir.getModel();
            temp2=(Cuenta)m.getSelectedItem();
            
            int monto=(Integer)sp_monto.getValue();

                if(temp.getSaldo()-monto>=0)
                {
                    aa.escribirArchivo();
                    ac=new adminCliente("./clientes.sas");
                    ac.cargarArchivo();
                    for (int i = 0; i < ac.getListaClientes().size(); i++) {
                        if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
                        {
                            for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                                if(ac.getListaClientes().get(i).getCuentas().get(j).equals(temp))
                                {
                                    ac.getListaClientes().get(i).getCuentas().get(j).setSaldo(ac.getListaClientes().get(i).getCuentas().get(j).getSaldo()-monto);
                                    Transaccion t = new Transaccion(ac.getListaClientes().get(i).getCuentas().get(j).getNombre(), x, "Transferencia a otra cuenta", new Date().toString());
                                    ac.getListaClientes().get(i).getMistransacciones().add(t);
                                    at=new adminTransaccion("./transacciones.txt");
                                    at.cargarArchivo();
                                    at.setTransaccion(t);
                                    at.escribirArchivo();
                                    break;
                                }
                            }
                            break;
                        }
                    }
                    for (int i = 0; i < ac.getListaClientes().size(); i++) {
                        if(ac.getListaClientes().get(i).equals(tempC))
                        {
                            for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                                if(ac.getListaClientes().get(i).getCuentas().get(j).equals(temp2))
                                {
                                    ac.getListaClientes().get(i).getCuentas().get(j).setSaldo(ac.getListaClientes().get(i).getCuentas().get(j).getSaldo()+monto);
                                    break;
                                }
                            }
                            break;
                        }
                    }
                    
                    ac.escribirArchivo();
                    JOptionPane.showMessageDialog(this, "transferencia exitosa");
                    jd_Cliente.dispose();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "La cuenta no tiene la cantidad de dinero necesaria");
                }
                sp_monto.setValue(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al ingresar los datos");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel m=new DefaultComboBoxModel();
        ac=new adminCliente("./clientes.sas");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getListaClientes().size(); i++) {
            if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
            {
                for (int j = 0; j < ac.getListaClientes().get(i).getCuentas().size(); j++) {
                    m.addElement(ac.getListaClientes().get(i).getCuentas().get(j));
                }
            }
        }
        cb_miCuenta3.setModel(m);
        jd_EstadoCuenta.setVisible(true);
        jd_EstadoCuenta.pack();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void cb_miCuenta3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_miCuenta3ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==2)
        {
            Cuenta temp;
            DefaultComboBoxModel m=(DefaultComboBoxModel)cb_miCuenta3.getModel();
            temp=(Cuenta)m.getSelectedItem();
            tf_miSaldo.setText(temp.getSaldo()+" Lps");
        }
    }//GEN-LAST:event_cb_miCuenta3ItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jd_Transacciones.setVisible(true);
        jd_Transacciones.pack();
        DefaultTableModel m = new DefaultTableModel();
        m.addColumn("Cuenta");
        m.addColumn("Accion");
        m.addColumn("Fecha");
        for (int i = 0; i < ((Cliente)current).getMistransacciones().size(); i++) {
            Object[] newrow={
                ((Cliente)current).getMistransacciones().get(i).getCuenta(),
                ((Cliente)current).getMistransacciones().get(i).getAccion(),
                ((Cliente)current).getMistransacciones().get(i).getFecha()
            };
            m.addRow(newrow);
        }
        jt_transacciones.setModel(m);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        try {
            int monto;
        String pass="";
        monto=(Integer)sp_100.getValue()*100+(Integer)sp_500.getValue()*500;
        aa=new adminATM("./ATM.sas");
        for (int i = 0; i < aa.getListaATM().size(); i++) {
            if(aa.getListaATM().get(i).equals(atm_actual))
            {
               aa.getListaATM().get(i).setDinero(aa.getListaATM().get(i).getDinero()+monto);
            }
            pass=JOptionPane.showInputDialog("Ingrese su clave para finalizar la transaccion y cerrar el sistema: ");
            while(!pass.equals(current.getContra()))
            {
                pass=JOptionPane.showInputDialog("Clave incorrecta, ingresela nuevamente: ");
            }
            Log l = new Log(current.getUser(), "Mantenimiento del ATM", String.valueOf(new Date().getDate()), String.valueOf(new Date().getHours()));
                    al=new adminLog("./log.txt");
                    al.cargarArchivo();
                    al.setLog(l);
                    al.escribirArchivo();
            jd_Mantenimiento.setVisible(false);
            sp_100.setValue(0);
            sp_500.setValue(0);
        }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton12MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            int x=999+rand.nextInt(9999);
            String cuenta;
            int monto;
            cuenta=JOptionPane.showInputDialog("Ingrese el nombre de la cuenta:");
            monto=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el saldo que le va a ingresar a la cuenta"));
            Cuenta c=new Cuenta(x, monto,current.getUser(), cuenta);
            ac=new adminCliente("./clientes.sas");
            ac.cargarArchivo();
            for (int i = 0; i < ac.getListaClientes().size(); i++) {
                if(ac.getListaClientes().get(i).getUser().equals(current.getUser()))
                {
                    System.out.println("hola");
                    ac.getListaClientes().get(i).getCuentas().add(c);
                }
            }
            ac.escribirArchivo();
            ((Cliente)current).getCuentas().add(c);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_retirar;
    private javax.swing.JComboBox<String> cb_ATM;
    private javax.swing.JComboBox<String> cb_cuentaTransferir;
    private javax.swing.JComboBox<String> cb_miCuenta;
    private javax.swing.JComboBox<String> cb_miCuenta1;
    private javax.swing.JComboBox<String> cb_miCuenta2;
    private javax.swing.JComboBox<String> cb_miCuenta3;
    private javax.swing.JComboBox<String> cb_transferir;
    private com.toedter.calendar.JDateChooser dc_afiliacion;
    private com.toedter.calendar.JDateChooser dc_afiliacion1;
    private com.toedter.calendar.JDateChooser dc_fabricacion;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private com.toedter.calendar.JDateChooser dc_fecha1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_ATM;
    private javax.swing.JDialog jd_Cliente;
    private javax.swing.JDialog jd_Crear;
    private javax.swing.JDialog jd_CrearMantenimiento;
    private javax.swing.JDialog jd_EstadoCuenta;
    private javax.swing.JDialog jd_Ingresar;
    private javax.swing.JDialog jd_Mantenimiento;
    private javax.swing.JDialog jd_Retirar;
    private javax.swing.JDialog jd_Transacciones;
    private javax.swing.JDialog jd_Transferencia;
    private javax.swing.JList<String> jl_ATM;
    private javax.swing.JTable jt_transacciones;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JRadioButton rb_100;
    private javax.swing.JRadioButton rb_100i;
    private javax.swing.JRadioButton rb_500;
    private javax.swing.JRadioButton rb_500i;
    private javax.swing.JSpinner sp_100;
    private javax.swing.JSpinner sp_500;
    private javax.swing.JSpinner sp_monto;
    private javax.swing.JTextField tf_apellido1;
    private javax.swing.JTextField tf_apellido1M;
    private javax.swing.JTextField tf_apellido2;
    private javax.swing.JTextField tf_apellido2M;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contra1;
    private javax.swing.JTextField tf_mantenimiento;
    private javax.swing.JTextField tf_miSaldo;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre1M;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre2M;
    private javax.swing.JTextField tf_ubicacion;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario1;
    // End of variables declaration//GEN-END:variables

    adminCliente ac;
    adminMantenimiento am;
    adminATM aa;
    adminLog al;
    adminTransaccion at;
    ArrayList<ATM> atms;
    Usuario current;
    ATM atm_actual;
    Random rand=new Random();
}
